/**
 * BLITZBALL X — live balance tuning panel (dev only).
 *
 * Activated with `?tune`. Balance work used to mean: guess a number, edit src/data/constants.js,
 * wait for a rebuild, play a few minutes of match, guess again. This panel edits the same constants
 * objects in place while the game runs, so a dial can be felt immediately — and it prints the diff
 * as paste-ready lines for the file, so a value that felt right does not have to be re-typed.
 *
 * What it can and cannot do:
 *   - The fields are generated by walking the constants objects themselves (see `collectFields`),
 *     so the panel can never fall behind a new dial. Nested groups (COMBAT.hitstop,
 *     MOVE.staminaContactDrain, each DIFFICULTY level) are walked one level deeper.
 *   - ARENA is deliberately not included: the arena's numbers are baked into the geometry, the
 *     camera and the water when a match is built, so editing them live would leave a pool that
 *     disagrees with its own rules.
 *   - RULES is copied into each sim at construction, so a rules change is pushed into the running
 *     match through MatchSim.syncTuning(). Everything else is read live from the module.
 *   - Nothing is persisted. Reloading the page is the reset button of record.
 *
 * The pure pieces (field discovery, slider bounds, diff formatting) are unit-tested in node; the
 * DOM panel is just a view over them.
 */
import { RULES, PHYS, MOVE, ACTION, STYLE, COMBAT, DIFFICULTY } from '../data/constants.js';

/** Editable roots, in panel order. ARENA intentionally absent (see the header). */
export const TUNE_ROOTS = [
  ['RULES', RULES],
  ['PHYS', PHYS],
  ['MOVE', MOVE],
  ['ACTION', ACTION],
  ['STYLE', STYLE],
  ['COMBAT', COMBAT],
  ['DIFFICULTY', DIFFICULTY],
];

const ROOT_BY_NAME = Object.fromEntries(TUNE_ROOTS);

const isPlainObject = (v) => !!v && typeof v === 'object' && !Array.isArray(v);

/** Split a dotted path into the object that owns the final key. */
function resolve(path) {
  const parts = String(path).split('.');
  let obj = ROOT_BY_NAME[parts[0]];
  if (!obj) throw new Error(`unknown tuning root: ${parts[0]}`);
  for (let i = 1; i < parts.length - 1; i++) obj = obj[parts[i]];
  return { obj, key: parts[parts.length - 1] };
}

export function readValue(path) {
  const { obj, key } = resolve(path);
  return obj[key];
}

export function writeValue(path, value) {
  const { obj, key } = resolve(path);
  obj[key] = value;
}

/**
 * Every numeric dial, as a dotted path, sorted so the panel reads predictably. Generated rather
 * than hand-listed: a curated list is one more thing to forget to update when a constant is added.
 */
export function collectFields(roots = TUNE_ROOTS) {
  const out = [];
  const walk = (path, obj) => {
    for (const [key, value] of Object.entries(obj)) {
      if (typeof value === 'number' && Number.isFinite(value)) out.push(`${path}.${key}`);
      else if (isPlainObject(value)) walk(`${path}.${key}`, value);
    }
  };
  for (const [name, obj] of roots) walk(name, obj);
  return out.sort();
}

export const FIELDS = collectFields();

/** Current value of every dial. */
export function snapshot() {
  const out = {};
  for (const path of FIELDS) out[path] = readValue(path);
  return out;
}

/** Dials that moved since `base` (defaults to a snapshot taken now). */
export function diffSnapshot(base, current = snapshot()) {
  const changed = [];
  for (const path of FIELDS) {
    if (current[path] !== base[path]) changed.push({ path, from: base[path], to: current[path] });
  }
  return changed;
}

/**
 * A diff as lines to paste into src/data/constants.js, grouped the way the file groups them. The
 * group header is the object path (DIFFICULTY.pro for a difficulty dial); the line is the bare key,
 * because that is exactly what the file contains.
 */
export function formatDiff(changes) {
  if (!changes.length) return '';
  const lines = [];
  let group = null;
  for (const c of changes) {
    const parts = c.path.split('.');
    const g = parts.length > 2 ? parts.slice(0, 2).join('.') : parts[0];
    if (g !== group) {
      if (group !== null) lines.push('');
      lines.push(`// ${g}`);
      group = g;
    }
    lines.push(`${parts[parts.length - 1]}: ${c.to},`);
  }
  return `${lines.join('\n')}\n`;
}

/**
 * Slider bounds derived from the value being edited: 0..2x for a positive dial, 2x..0 for a
 * negative one (gravity), with a step fine enough that a sub-1 multiplier is actually reachable.
 * The number box beside the slider takes exact values, so these bounds never cap a dial.
 */
export function sliderRange(value) {
  const v = Number(value);
  if (!Number.isFinite(v) || v === 0) return { min: 0, max: 1, step: 0.01 };
  if (v < 0) return { min: v * 2, max: 0, step: Math.abs(v) >= 10 ? 1 : 0.1 };
  return { min: 0, max: v * 2, step: v >= 100 ? 1 : v >= 10 ? 0.1 : v >= 1 ? 0.01 : 0.001 };
}

/** Same convention as `?bench`, `?diag` and `?perf`. */
export function tuningEnabled(loc = typeof window === 'undefined' ? null : window.location) {
  try {
    return !!loc && new URLSearchParams(loc.search).has('tune');
  } catch {
    return false;
  }
}

const STYLE_SHEET = {
  panel: 'position:fixed;top:8px;right:8px;z-index:9997;width:352px;max-height:calc(100vh - 16px);'
    + 'display:flex;flex-direction:column;background:rgba(4,12,20,0.94);color:#dff6ff;'
    + 'border:1px solid rgba(143,247,255,0.35);border-radius:8px;'
    + 'font:11px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace',
  head: 'padding:7px 9px;border-bottom:1px solid rgba(143,247,255,0.25);display:flex;flex-wrap:wrap;gap:5px;align-items:center',
  // min-height:0 is load-bearing: without it a scrolled flex child refuses to shrink below its
  // content, so 188 dials would push the diff box off the bottom of the panel.
  list: 'overflow:auto;flex:1 1 auto;min-height:0;padding:4px 9px 8px',
  row: 'display:flex;align-items:center;gap:6px;padding:1px 0',
  label: 'flex:1 1 auto;white-space:nowrap;overflow:hidden;text-overflow:ellipsis',
  group: 'margin:7px 0 2px;color:#8ff7ff;letter-spacing:0.06em',
  range: 'width:88px',
  num: 'width:62px;background:#06131f;color:#dff6ff;border:1px solid rgba(143,247,255,0.28);border-radius:3px;font:inherit;padding:1px 3px',
  btn: 'background:#0d2130;color:#8ff7ff;border:1px solid rgba(143,247,255,0.4);border-radius:4px;'
    + 'font:inherit;padding:2px 7px;cursor:pointer',
  // flex:none keeps the diff box at its own height: as a shrinkable flex item next to a 188-row
  // list it was being squeezed to a single visible line.
  diff: 'flex:none;width:100%;height:76px;margin-top:6px;background:#06131f;color:#9fe8b0;'
    + 'border:1px solid rgba(143,247,255,0.28);border-radius:4px;font:10px/1.35 ui-monospace,monospace',
};

/**
 * The panel. `onChange(path)` fires after every edit so the app can push rules into a live match;
 * the panel itself never reaches into game state.
 */
export class TuningPanel {
  constructor({ parent = document.body, onChange = () => {} } = {}) {
    this.onChange = onChange;
    this.base = snapshot();
    this.touched = new Set();
    this.rows = new Map();
    this.headers = [];

    this.el = document.createElement('div');
    this.el.id = 'tune-panel';
    this.el.style.cssText = STYLE_SHEET.panel;

    const head = document.createElement('div');
    head.style.cssText = STYLE_SHEET.head;

    const title = document.createElement('strong');
    title.textContent = 'TUNE';
    head.appendChild(title);

    const search = document.createElement('input');
    search.type = 'search';
    search.placeholder = 'filter…';
    search.style.cssText = `${STYLE_SHEET.num}width:auto;flex:1 1 90px`;
    search.addEventListener('keydown', (e) => e.stopPropagation()); // the game listens on window
    search.addEventListener('input', () => this.filter(search.value));
    head.appendChild(search);

    this.countEl = document.createElement('span');
    this.countEl.textContent = '0 changed';
    head.appendChild(this.countEl);

    const reset = document.createElement('button');
    reset.textContent = 'RESET';
    reset.style.cssText = STYLE_SHEET.btn;
    reset.addEventListener('click', () => this.reset());
    head.appendChild(reset);

    const copy = document.createElement('button');
    copy.textContent = 'COPY DIFF';
    copy.style.cssText = STYLE_SHEET.btn;
    this.statusEl = document.createElement('span');
    this.statusEl.textContent = '';
    copy.addEventListener('click', async () => {
      const text = this.diffText();
      if (!text) {
        this.statusEl.textContent = 'nothing changed';
        return;
      }
      try {
        await navigator.clipboard.writeText(text);
        this.statusEl.textContent = 'copied';
      } catch {
        // Clipboard access can be denied (no user gesture, insecure origin): the diff box below is
        // the fallback, so the work is never trapped in the panel.
        this.diffEl.focus();
        this.diffEl.select();
        this.statusEl.textContent = 'select + copy below';
      }
    });
    head.appendChild(copy);
    head.appendChild(this.statusEl);

    this.el.appendChild(head);

    this.list = document.createElement('div');
    this.list.style.cssText = STYLE_SHEET.list;
    this.el.appendChild(this.list);

    this.diffEl = document.createElement('textarea');
    this.diffEl.readOnly = true;
    this.diffEl.spellcheck = false;
    this.diffEl.placeholder = 'changed dials, as lines for src/data/constants.js';
    this.diffEl.style.cssText = STYLE_SHEET.diff;
    this.diffEl.addEventListener('keydown', (e) => e.stopPropagation());
    this.el.appendChild(this.diffEl);

    this.buildRows();
    parent.appendChild(this.el);
  }

  buildRows() {
    let group = null;
    for (const path of FIELDS) {
      const parts = path.split('.');
      const g = parts.length > 2 ? parts.slice(0, 2).join('.') : parts[0];
      if (g !== group) {
        group = g;
        const header = document.createElement('div');
        header.style.cssText = STYLE_SHEET.group;
        header.textContent = g;
        this.headers.push(header);
        this.list.appendChild(header);
      }
      this.rows.set(path, this.buildRow(path));
    }
  }

  buildRow(path) {
    const value = readValue(path);
    const row = document.createElement('div');
    row.style.cssText = STYLE_SHEET.row;

    const label = document.createElement('label');
    label.textContent = path.split('.').slice(-1)[0];
    label.title = path;
    label.style.cssText = STYLE_SHEET.label;
    label.htmlFor = `tune-${path}`;
    row.appendChild(label);

    const range = document.createElement('input');
    range.type = 'range';
    range.id = `tune-${path}`;
    range.style.cssText = STYLE_SHEET.range;
    const bounds = sliderRange(value);
    range.min = String(bounds.min);
    range.max = String(bounds.max);
    range.step = String(bounds.step);
    range.value = String(value);
    row.appendChild(range);

    const num = document.createElement('input');
    num.type = 'number';
    num.step = 'any';
    num.value = String(value);
    num.style.cssText = STYLE_SHEET.num;
    num.addEventListener('keydown', (e) => e.stopPropagation());
    row.appendChild(num);

    const commit = (raw) => {
      const next = Number(raw);
      if (!Number.isFinite(next)) return;
      writeValue(path, next);
      range.value = String(next);
      num.value = String(next);
      this.markChanged(path, row, label);
      this.onChange(path);
    };
    range.addEventListener('input', () => commit(range.value));
    num.addEventListener('change', () => commit(num.value));
    this.list.appendChild(row);
    return row;
  }

  markChanged(path, row, label) {
    const changed = readValue(path) !== this.base[path];
    if (changed) this.touched.add(path);
    else this.touched.delete(path);
    row.style.background = changed ? 'rgba(255,138,61,0.14)' : '';
    label.style.color = changed ? '#ffc38a' : '';
    this.countEl.textContent = `${this.touched.size} changed`;
    this.countEl.style.color = this.touched.size ? '#ffc38a' : '';
    this.diffEl.value = this.diffText();
  }

  diffText() {
    return formatDiff(diffSnapshot(this.base));
  }

  filter(query) {
    const q = String(query).trim().toLowerCase();
    for (const [path, row] of this.rows) {
      row.style.display = !q || path.toLowerCase().includes(q) ? '' : 'none';
    }
    // Group headers are noise while filtering (the surviving rows already say what they are).
    for (const header of this.headers) header.style.display = q ? 'none' : '';
  }

  /** Put every dial back to where it was when the panel opened. */
  reset() {
    for (const path of FIELDS) {
      const value = this.base[path];
      writeValue(path, value);
      const row = this.rows.get(path);
      if (!row) continue;
      const [range, num] = row.querySelectorAll('input');
      range.value = String(value);
      num.value = String(value);
    }
    this.touched.clear();
    for (const [path, row] of this.rows) this.markChanged(path, row, row.querySelector('label'));
    this.onChange('*');
  }

  dispose() {
    this.el.remove();
  }
}

/**
 * Mount the panel when `?tune` is set. Returns null on a normal load, so the game is untouched.
 * window.__BB_TUNE__ exposes the same pure helpers the panel uses, for scripting a sweep.
 */
export function startTuning(app) {
  if (!tuningEnabled()) return null;
  const sync = () => app?.match?.sim?.syncTuning?.();
  const panel = new TuningPanel({ onChange: sync });
  window.__BB_TUNE__ = {
    panel,
    fields: FIELDS.slice(),
    roots: TUNE_ROOTS.map(([name]) => name),
    snapshot,
    read: readValue,
    write: (path, value) => {
      const changed = writeValue(path, value);
      const row = panel.rows.get(path);
      if (row) panel.markChanged(path, row, row.querySelector('label'));
      sync();
      return changed;
    },
    diff: () => diffSnapshot(panel.base),
    formatDiff,
    reset: () => panel.reset(),
  };
  return panel;
}
